site_name: Spatiotemporal Wildlife Classification Docs

theme:
  name: "material"

plugins:
- mkdocstrings:
    default_handler: python

nav:
  - Organization Home: https://spatiotemporal-wildlife-classification.github.io/
  - Home: index.md
  - Code Documentation: src.md
  - Dataset : dataset.md
  - Novel Cascading Ensemble Classifier: cascading_ensemble_classifier.md
  - Results: results.md
  - Thesis report: thesis.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js